# Generated by Django 3.2.8 on 2021-10-24 05:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('phone_number', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('apt', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('provider_name', models.CharField(max_length=50)),
                ('plan_name', models.CharField(max_length=50)),
                ('rx_bin', models.IntegerField(blank=True, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('rx_pcn', models.IntegerField(blank=True, null=True)),
                ('rx_group', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
