# Generated by Django 3.2.8 on 2021-10-26 02:27

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(blank=True, max_length=50, null=True)),
                ('aller_drug', models.CharField(blank=True, max_length=20, null=True)),
                ('aller_severity', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('u_name', models.CharField(blank=True, max_length=50, null=True)),
                ('appointment_comments', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('charge_date', models.DateField(blank=True, null=True)),
                ('doc_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('medi_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('room_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('surgery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('admission_days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nursing_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('advance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('test_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('diagnosis_status', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_comment', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('ins_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_copay', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ins_plan', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_rx_bin', models.CharField(blank=True, max_length=10, null=True)),
                ('ins_rx_pcn', models.CharField(blank=True, max_length=10, null=True)),
                ('ins_rx_group', models.CharField(blank=True, max_length=20, null=True)),
                ('ins_coverage', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ins_copay', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pay_description', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phys_Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_contents', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('rx_date', models.DateField(blank=True, null=True)),
                ('rx_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rx_dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('rx_sig', models.CharField(blank=True, max_length=300, null=True)),
                ('rx_comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('s_f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('s_l_name', models.CharField(blank=True, max_length=50, null=True)),
                ('s_affiliation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vac_date', models.DateField(blank=True, null=True)),
                ('vac_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vac_comment', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('vt_date', models.DateField(blank=True, null=True)),
                ('vt_bloodgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('vt_bp_sys', models.IntegerField(blank=True, null=True)),
                ('vt_bp_dia', models.IntegerField(blank=True, null=True)),
                ('vt_wbc', models.IntegerField(blank=True, null=True)),
                ('vt_rbc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('vt_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vt_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vt_comments', models.CharField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('phone_number', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('apt', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
