# Generated by Django 3.2.8 on 2021-10-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('aller_id', models.AutoField(primary_key=True, serialize=False)),
                ('aller_drug', models.CharField(max_length=20)),
                ('aller_severity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('u_name', models.CharField(max_length=50)),
                ('appointment_comments', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('charge_date', models.DateField()),
                ('doc_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medi_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('surgery_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('admission_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nursing_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('test_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_no', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('diagnosis_date', models.DateField()),
                ('diagnosis_status', models.CharField(max_length=100)),
                ('diagnosis_comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('ins_mem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('ins_name', models.CharField(max_length=100)),
                ('ins_copay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_plan', models.CharField(max_length=100)),
                ('ins_rx_bin', models.CharField(max_length=10)),
                ('ins_rx_pcn', models.CharField(max_length=10)),
                ('ins_rx_group', models.CharField(max_length=20)),
                ('ins_coverage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('pay_date', models.DateField()),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_copay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_description', models.CharField(max_length=100)),
                ('pay_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phys_Orders',
            fields=[
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('order_contents', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('rx_no', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('rx_date', models.DateField()),
                ('rx_name', models.CharField(max_length=100)),
                ('rx_dosage', models.CharField(max_length=100)),
                ('rx_sig', models.CharField(max_length=300)),
                ('rx_comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('s_f_name', models.CharField(max_length=50)),
                ('s_l_name', models.CharField(max_length=50)),
                ('s_affiliation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('vac_date', models.DateField()),
                ('vac_type', models.CharField(max_length=100)),
                ('vac_comment', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vt_no', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=50)),
                ('vt_bloodgroup', models.CharField(max_length=50)),
                ('vt_bp_sys', models.IntegerField()),
                ('vt_bp_dia', models.IntegerField()),
                ('vt_wbc', models.IntegerField()),
                ('vt_rbc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vt_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vt_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vt_comments', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
    ]
