# Generated by Django 3.2.8 on 2021-10-26 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_allergies_appointment_bills_diagnosis_insurance_payment_phys_orders_prescription_staff_vaccines_vita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergies',
            name='aller_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis_no',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='ins_mem_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pay_id',
        ),
        migrations.RemoveField(
            model_name='phys_orders',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='rx_no',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='vac_id',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='vt_no',
        ),
        migrations.AddField(
            model_name='allergies',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergies',
            name='u_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bills',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phys_orders',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccines',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitals',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitals',
            name='vt_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='aller_drug',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='aller_severity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_comments',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='u_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='admission_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='doc_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='medi_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='nursing_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='room_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='surgery_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='test_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_copay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_coverage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_rx_bin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_rx_group',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='ins_rx_pcn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plan_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rx_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rx_pcn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(default=123, max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='ins_copay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phys_orders',
            name='order_contents',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phys_orders',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_sig',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_f_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_l_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='u_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='vac_comment',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='vac_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='vac_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_bloodgroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_bp_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_bp_sys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_comments',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_rbc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_wbc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
