# Generated by Django 3.2.8 on 2021-10-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211025_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='apt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
