# Generated by Django 3.2.8 on 2021-11-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='u_name',
            field=models.EmailField(max_length=50),
        ),
    ]
