# Generated by Django 3.2.8 on 2021-10-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(default=120, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='rx_bin',
            field=models.IntegerField(default=120, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='rx_pcn',
            field=models.IntegerField(default=120, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.IntegerField(default=120, max_length=50),
            preserve_default=False,
        ),
    ]
