# Generated by Django 3.2.7 on 2021-10-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presciption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pr_Date', models.DateField()),
                ('Pr_Medication', models.CharField(max_length=50)),
                ('Pr_Comments', models.CharField(max_length=50)),
            ],
        ),
    ]
