# Generated by Django 3.2.7 on 2021-10-19 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medi_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('surgery_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('admission_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nursing_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('test_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_no', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField()),
                ('diagnosis_status', models.CharField(max_length=100)),
                ('diagnosis_comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
                ('p_f_name', models.CharField(blank=True, default='', max_length=100)),
                ('p_l_name', models.CharField(blank=True, default='', max_length=100)),
                ('p_dob', models.DateField(blank=True, default='')),
                ('p_gender', models.CharField(blank=True, default='', max_length=100)),
                ('p_city', models.CharField(blank=True, default='', max_length=100)),
                ('p_state', models.CharField(blank=True, default='', max_length=100)),
                ('p_zipcode', models.IntegerField(blank=True, default='')),
                ('p_language', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('vt_no', models.IntegerField(primary_key=True, serialize=False)),
                ('vt_date', models.DateField()),
                ('vt_bloodgroup', models.CharField(max_length=100)),
                ('vt_bp_sys', models.IntegerField()),
                ('vt_bp_dia', models.IntegerField()),
                ('vt_wbc', models.IntegerField()),
                ('vt_rbc', models.IntegerField()),
                ('vt_height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vt_weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vt_comments', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_V', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('vac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vac_date', models.DateField()),
                ('vac_type', models.CharField(max_length=100)),
                ('vac_comment', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_Vac', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cedus',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_id_U', to='patient.user_role')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('surgery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surgery_date', models.DateField()),
                ('surgery_description', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_S', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('s_id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
                ('s_f_name', models.CharField(blank=True, default='', max_length=100)),
                ('s_l_name', models.CharField(blank=True, default='', max_length=100)),
                ('s_affiliation', models.CharField(blank=True, default='', max_length=100)),
                ('role_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='role_id_S', to='patient.user_role')),
                ('user_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_id_S', to='patient.user_cedus')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('rx_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rx_date', models.DateField()),
                ('rx_dosage', models.CharField(max_length=100)),
                ('rx_comments', models.CharField(max_length=100)),
                ('diagnosis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diag_no_rx', to='patient.diagnosis')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id_rx', to='patient.user_cedus')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_copay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_description', models.CharField(max_length=100)),
                ('pay_location', models.CharField(max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_id_P', to='patient.bills')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_id_P', to='patient.user_cedus'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('ins_mem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ins_name', models.CharField(max_length=100)),
                ('ins_copay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_plan', models.CharField(max_length=100)),
                ('ins_rx_bin', models.CharField(max_length=10)),
                ('ins_rx_pcn', models.CharField(max_length=10)),
                ('ins_rx_group', models.CharField(max_length=20)),
                ('ins_coverage', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_Ins', to='patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_Diag', to='patient.patient'),
        ),
        migrations.AddField(
            model_name='bills',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_B', to='patient.patient'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_loc', models.CharField(max_length=100)),
                ('appointment_comments', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_Appo', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('aller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aller_to', models.CharField(max_length=100)),
                ('aller_comments', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_id_A', to='patient.patient')),
            ],
        ),
    ]
