# Generated by Django 3.2.8 on 2021-10-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cedus',
            name='phone_num',
            field=models.CharField(max_length=100),
        ),
    ]
