# Generated by Django 3.2.8 on 2021-10-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_user_cedus_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_P', to='patient.user_cedus'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_id_S', to='patient.user_role'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_S', to='patient.user_cedus'),
        ),
        migrations.AlterField(
            model_name='user_cedus',
            name='user_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
