# Generated by Django 3.2.8 on 2021-10-19 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_P', to='patient.user_cedus'),
        ),
        migrations.AlterField(
            model_name='user_role',
            name='role_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
