# Generated by Django 3.2.8 on 2021-10-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20211019_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user_cedus',
            name='role_id',
        ),
    ]
