# Generated by Django 3.2.8 on 2021-10-19 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20211019_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id_P', to='patient.user_cedus'),
        ),
        migrations.AddField(
            model_name='user_cedus',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_id_U', to='patient.user_role'),
        ),
        migrations.AlterField(
            model_name='user_cedus',
            name='user_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
