# Generated by Django 3.2.8 on 2021-10-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20211019_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis_no',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='surgeries',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='user_cedus',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='p_id',
        ),
        migrations.DeleteModel(
            name='Allergies',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Bills',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Surgeries',
        ),
        migrations.DeleteModel(
            name='User_Cedus',
        ),
        migrations.DeleteModel(
            name='Vaccines',
        ),
        migrations.DeleteModel(
            name='Vitals',
        ),
    ]
