# Generated by Django 3.2.8 on 2021-10-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20211019_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Cedus',
            fields=[
                ('user_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('user_password', models.CharField(blank=True, max_length=100)),
                ('phone_num', models.CharField(blank=True, max_length=100)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user_role')),
            ],
        ),
    ]
