# Generated by Django 3.2.8 on 2021-10-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_user_cedus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('p_f_name', models.CharField(blank=True, default='', max_length=100)),
                ('p_l_name', models.CharField(blank=True, default='', max_length=100)),
                ('p_dob', models.DateField(blank=True, default='')),
                ('p_gender', models.CharField(blank=True, default='', max_length=100)),
                ('p_city', models.CharField(blank=True, default='', max_length=100)),
                ('p_state', models.CharField(blank=True, default='', max_length=100)),
                ('p_zipcode', models.IntegerField(blank=True, default='')),
                ('p_language', models.CharField(blank=True, default='', max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user_cedus')),
            ],
        ),
    ]
