# Generated by Django 3.2.8 on 2021-10-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('s_id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
                ('s_f_name', models.CharField(blank=True, default='', max_length=100)),
                ('s_l_name', models.CharField(blank=True, default='', max_length=100)),
                ('s_affiliation', models.CharField(blank=True, default='', max_length=100)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user_role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user_cedus')),
            ],
        ),
    ]
