# Generated by Django 3.2.8 on 2021-10-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('aller_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aller_to', models.CharField(max_length=100)),
                ('aller_comments', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
