# Generated by Django 3.2.8 on 2021-10-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_vitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('vac_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vac_date', models.DateField()),
                ('vac_type', models.CharField(max_length=100)),
                ('vac_comment', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
