# Generated by Django 3.2.8 on 2021-10-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_vaccines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis_no', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateField()),
                ('diagnosis_status', models.CharField(max_length=100)),
                ('diagnosis_comment', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
