# Generated by Django 3.2.8 on 2021-10-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('rx_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rx_date', models.DateField()),
                ('rx_dosage', models.CharField(max_length=100)),
                ('rx_comments', models.CharField(max_length=100)),
                ('diagnosis_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.diagnosis')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user_cedus')),
            ],
        ),
    ]
