# Generated by Django 3.2.8 on 2021-10-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medi_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('surgery_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('admission_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nursing_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('test_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Surgeries',
            fields=[
                ('surgery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surgery_date', models.DateField()),
                ('surgery_description', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pay_date', models.DateField()),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_copay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pay_description', models.CharField(max_length=100)),
                ('pay_location', models.CharField(max_length=100)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.bills')),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('ins_mem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ins_name', models.CharField(max_length=100)),
                ('ins_copay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ins_plan', models.CharField(max_length=100)),
                ('ins_rx_bin', models.CharField(max_length=10)),
                ('ins_rx_pcn', models.CharField(max_length=10)),
                ('ins_rx_group', models.CharField(max_length=20)),
                ('ins_coverage', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_loc', models.CharField(max_length=100)),
                ('appointment_comments', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
