# Generated by Django 3.2.8 on 2021-10-19 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_appointment_bills_insurance_payment_surgeries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergies',
            name='aller_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bills',
            name='bill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='rx_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(11111)]),
        ),
        migrations.AlterField(
            model_name='surgeries',
            name='surgery_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccines',
            name='vac_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_rbc',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
