# Generated by Django 3.2.8 on 2021-10-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20211019_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='vt_comments',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
