# Generated by Django 3.2.8 on 2021-10-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_alter_vitals_vt_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='vt_height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_rbc',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='vt_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
