# Generated by Django 3.2.8 on 2021-10-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_auto_20211019_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='rx_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
