# Generated by Django 3.2.7 on 2021-10-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnosis_Date', models.DateField()),
                ('Diagnosis_Status', models.DateField()),
                ('Diagnosis_Comment', models.DateField()),
            ],
        ),
    ]
